apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zdom
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zdom
    app.kubernetes.io/part-of: tkrw-pr712-0075-0042-app
  name: devfile-sample-zdom
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zdom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zdom
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-zdom@sha256:3e7d2bee756639876e3b7a52c9357c68c25ad00625c8a504fe3b25f8de9833cb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
